name: medical_house
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.10.0

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  provider: ^6.1.1
  shared_preferences: ^2.2.2
  image_picker: ^1.0.4
  crystal_navigation_bar: ^1.0.4
  dio: ^5.8.0+1
  flutter_secure_storage: ^8.0.0
  url_launcher: ^6.1.7
  google_maps_flutter: ^2.2.5
  mobile_scanner: ^5.2.3
  latlong2: ^0.9.0
  # UPDATED THIS LINE:
  geolocator: ^10.1.0 
  geocoding: ^2.1.1
  permission_handler: ^11.3.0
  photo_view: ^0.15.0
  web_socket_channel: ^3.0.3
  dots_indicator: ^3.0.0
  get: ^4.6.6
  flutter_dotenv: ^5.1.0
  get_storage: ^2.1.1
  smooth_page_indicator: ^1.2.1
  shimmer: ^3.0.0
  fl_chart: ^0.65.0
  flutter_image_compress: ^2.4.0
  flutter_screenutil: ^5.9.3
  app_tracking_transparency: ^2.0.4
  flutter_dynamic_icon_plus: ^1.4.0
  upgrader: ^12.5.0
  firebase_core: ^4.4.0
  firebase_messaging: ^16.1.1
  http: ^1.1.2 
  video_player: ^2.8.2
  location: ^5.0.3
  open_street_map_search_and_pick: 0.1.1
  flutter_map: ^6.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

# This section forces the older package to work with your newer lints
dependency_overrides:
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true

  assets:
    - lib/Assets/Images/
    - lib/Assets/Icons/
    - lib/Assets/
    - keys.env