platform :ios, '15.0'

# CocoaPods analytics sends network stats so CocoaPods authors can debug
# dependency problems. Learn more at https://guides.cocoapods.org/syntax/podfile.html#install_method
install! 'cocoapods', :deterministic_uuids => false

target 'Runner' do
  use_frameworks!
  use_modular_headers!

  flutter_install_all_ios_pods File.dirname(File.realpath(__FILE__))
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    flutter_additional_ios_build_settings(target)
    target.build_configurations.each do |config|
      # This ensures all plugins also target iOS 15.0
      config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '15.0'
    end
  end
end